name: GithubActions--Workflow-Dispatch-Input

on:
  workflow_dispatch:
    inputs:
      numOne:
        description: 'Enter first number:'
        required: true
      numTwo:
        description: 'Enter second number:'
        required: true

env:
  firstNum : ${{github.event.inputs.numOne}}
  secondNum : ${{github.event.inputs.numTwo}}

jobs:
  pythonScripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
        
      - name: Run python script for prime number and add number
        run: |
          python prime.py $firstNum $secondNum
          python add.py $firstNum $secondNum