# This is a basic workflow to help you get started with Actions
name: GithubActions--Workflow-Dispatch-Input

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      numOne:
        description: 'Enter first number:'
        required: true
      numTwo:
        description: 'Enter second number:'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
        env:
          firstNum : github.event.inputs.numOne
          secondNum : github.event.inputs.numTwo
      # Runs a set of commands using the runners shell
      - name: Run python script for prime number
        run: |
          python prime.py $firstNum $secondNum
          python add.py $firstNum $secondNum

      # # Runs a single command using the runners shell
      # - name: Run python script for add number
      #   run: 
      #     p
